### ISSUE TITLE
Работа со шрифтами

### ISSUE THREAD

**Issue by chikunov** [AndreyChuprin/Site-project#2]
Придумать текстовую строку и выполнить следующие операции: 
- [x] Вывести текст во всех возможных заголовочных тегах (h1 etc), все теги одновременно, каждый на своей строке.
- [x] Вывести каждую строку разным цветом
- [x] Использовать шрифт [Roboto](https://fonts.google.com/specimen/Roboto) для половины строк и [Open Sans](https://fonts.google.com/specimen/Open+Sans) для второй половины строк
- [x] Вывести последнюю строку наклонным начертанием
- [x] Вывести предпоследнюю строку жирным
- [x] Вывести одну из строк подчеркнутой
- [x] Задать размер любой из строк в 16px
- [x] Задать размер любой из строк в 2em и объяснить что это значит
- [x] Задать размер любой из строк в 2rem и объяснить что это значит
- [x] Задать размер любой из строк в 100% и объяснить что это значит
- [x] Задать размер любой из строк в 1vw и объяснить что это значит
- [x] Вывести любую из строк только большими буквами (upper-case)

**Comment by AndreyChuprin** [comment]
task №2 completed
