### ISSUE TITLE
Блочная модель

### ISSUE THREAD

**Issue by chikunov** [AndreyChuprin/Site-project#3]
- [x] Объяснить в чем разница между content-box и border-box свойства box-sizing
- [x] Сделать блок размера 150х40, сделать у него внутренний отступ в 10px и закрасить серым цветом
- [x] Добавить границу слева для предыдущего блока. Сделать ее красной
- [x] Сделать блок, у которого задана только высота = 80px. Установить ему внутренний отступ в 5px и внешний отступ слева в 10px. Объяснить чему равна ширина.
- [x] Вывести блок под предыдущим и сделать вертикальный отступ между ними в 15px.
- [x] Вывести блок размера 200х300. Внутри него сделать другой блок занимающий всю ширину и высоту родителя. Объяснить что произойдет если высота не указана.

**Comment by AndreyChuprin** [comment]
Task #3 Блочная модель выполненно
